# Generated by Django 3.2.7 on 2021-09-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_contact_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_favourite',
        ),
    ]
